// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(document).ready(function($) {
    var projects;
    projects = [];
    $.getJSON('/data/projects.json', function(data) {
      return $.each(data.projects, function(i, f) {
        var project;
        project = '<div class="slide" data-project-id="' + f.projectID + '"><img src="' + f.thumb + '" alt="' + f.title + '" /><span>' + f.title + '</span></div>';
        return $(project).appendTo("#project-carousel .strip");
      });
    });
    return $(window).bind("load", function() {
      return $('#project-carousel').carouselize();
    });
  });

}).call(this);
